sudo: required
services:
  - docker
language: go
go:
  - 1.6
env:
  - GO15VENDOREXPERIMENT=1
before_install:
  - go get github.com/Masterminds/glide
install:
  - case $TRAVIS_BRANCH in master) glide -y glide.yml install ;; dev) glide -y glide-dev.yml install ;; esac
  - bash /vendor/github.com/TF2Stadium/Helen/build_assets.bash
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
  - make static -B
  - case $TRAVIS_BRANCH in master) docker build -t tf2stadium/pauling:latest . ;; dev) docker build -t tf2stadium/pauling:dev . ;; esac 
after_success:
  - case $TRAVIS_BRANCH in master) docker push tf2stadium/pauling:latest ;; dev) docker push tf2stadium/pauling ;; esac
